### ISSUE TITLE
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'debug'

### ISSUE THREAD

**Issue by mariohmol** [agronholm/apscheduler#143]
Hi there,

i'm using Pyhon2.6 with Flask and APScheduler (3.1.0).

Using local dont seems to give this error, but in production site shows me that.

The error that gives the error from scheduler.py is:
*             logger.debug('Looking for jobs to run')

Am I obligated to have logger set? Shouldnt code prevent this error to occur?

bests

```
Exception in thread APScheduler (most likely raised during interpreter shutdown):
Traceback (most recent call last):
File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
File "/usr/lib64/python2.6/threading.py", line 484, in run
File "/usr/lib64/python2.6/site-packages/apscheduler/scheduler.py", line 579, in _main_loop
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'debug'
```

**Comment by anoopkhandelwal** [comment]
Set proper logging settings for root longer ,hope that works

**Comment by agronholm** [comment]
How did you manage to get this error? You must've explicitly set the logger to None. You can't do that.

**Comment by mariohmol** [comment]
i really dont know how it happened.. i have a logger in app.. it writes some erros on log.. would be better if the apscheduler check logger before use it?

**Comment by agronholm** [comment]
Why? Should it also check if the job stores, executors and locks are still in place every step of the way?

Nobody else has ever had this problem. The question is, how did `_logger` end up being `None` in your scheduler?

**Comment by mariohmol** [comment]
Is obligated to a app to have logger?

I didnt know that!

**Comment by mariohmol** [comment]
I think that i'm in wrong repo.. cause i couldnt find this line in this repo.. sorry. closing issue

**Comment by agronholm** [comment]
Couldn't find what line?

**Comment by mariohmol** [comment]
I mean, I made a confusion here..

Anyway, now i'm using the 3.1 version, but with some problems.

Local i'm getting:

>   from apscheduler.scheduler import Scheduler
>   File "/Library/Python/2.7/site-packages/apscheduler/scheduler.py", line 13, in <module>
>     from apscheduler.triggers import SimpleTrigger, IntervalTrigger, CronTrigger
> ImportError: cannot import name SimpleTrigger

And in server side i'm having :  

>  from apscheduler.scheduler import Scheduler
> File "/usr/lib64/python2.6/site-packages/apscheduler/__init__.py", line 3, in <module>,

**Comment by agronholm** [comment]
The `apscheduler.scheduler` module does not exist in 3.x. You're using 2.x there.

**Comment by mariohmol** [comment]
you are right.. in server i have to use py2.6 and looks like that 3.x do not work on py2.6.. i will try to upgrade server.. (but i'm having problem to compile wsgi in py2.7 on server).

Version 2.x is givin me this logger null error, it shows the error just inside the job.. like 3 lines up logger works.. 

anyway.. thanks for u help!
