### ISSUE TITLE
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'now'

### ISSUE THREAD

**Issue by jfach** [agronholm/apscheduler#301]
Hi, I'm trying to integrate APScheduler into my application, and have written a test script to play around and get a feel for things. I haven't been able to add a job yet as I keep running into this issue when I run my script, `scheduler.py`.

```
(apscheduler-test-env) jordan@jordan-mint ~/ap-scheduler-test-app $ python scheduler.py 
Exception in thread APScheduler (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/jordan/virtualenvs/apscheduler-test-env/local/lib/python2.7/site-packages/apscheduler/schedulers/blocking.py", line 30, in _main_loop
  File "/home/jordan/virtualenvs/apscheduler-test-env/local/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 927, in _process_jobs
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'now'
```

I'm running Python 2.7 and am working with APScheduler version 3.5.1

If you'd like to try and reproduce, I've also attached a copy of my script here:
```
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from apscheduler.executors.pool import ThreadPoolExecutor

sqlalchemy_job_store = SQLAlchemyJobStore(url='sqlite:////tmp/ap.db', tablename='scheduler')
job_stores = {'default': sqlalchemy_job_store}
executors = {'default': ThreadPoolExecutor(20)}
scheduler = BackgroundScheduler(job_stores=job_stores, executors=executors)


def add(x, y):
    print "adding..."
    return x + y


scheduler.start()
scheduler.add_job(add, 'interval', args=(6, 6), seconds=30)
```

I've taken a look at `schedulers/base.py` and everything seems to check out there, leaving me a bit confused. Thanks in advance and please let me know if you need me to provide any other information.

**Comment by jfach** [comment]
I've commented the last two lines out of the script and then did the following in the interpreter: 

```
>>> import scheduler as s
>>> scheduler = s.scheduler
>>> scheduler.start()
>>> scheduler.add_job(s.add, 'interval', args=(6, 6), seconds=30)
<Job (id=e75c4200e625435dbb0a666d51c83782 name=add)>
```

Additionally, no table was created in my database and the job doesn't seem to actually be running, as the output of `scheduler.print_jobs()` is consistently: 
```
>>> scheduler.print_jobs()
Jobstore default:
    add (trigger: interval[0:00:30], next run at: 2018-04-02 14:52:34 EDT)
```

**Comment by jfach** [comment]
Quick update:

Changing the name of my script from `scheduler.py` to `myscheduler.py` yields the following results:

```
(apscheduler-test-env) jordan@jordan-mint ~/ap-scheduler-test-app $ python myscheduler.py
Exception in thread APScheduler (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/jordan/virtualenvs/apscheduler-test-env/local/lib/python2.7/site-packages/apscheduler/schedulers/blocking.py", line 28, in _main_loop
  File "/usr/lib/python2.7/threading.py", line 614, in wait
  File "/usr/lib/python2.7/threading.py", line 355, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

**Comment by agronholm** [comment]
I don't understand how your example script could possibly have worked for you. You're using `BackgroundScheduler` there, which of course does not block the script from exiting so it exits right after you start it. When I replaced it with `BlockingScheduler` and moved the `scheduler.start()` line after the `scheduler.add_job()` line, it all works as expected. Please try with the attached script.
```
import logging

from apscheduler.schedulers.blocking import BlockingScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from apscheduler.executors.pool import ThreadPoolExecutor

sqlalchemy_job_store = SQLAlchemyJobStore(url='sqlite:////tmp/ap.db', tablename='scheduler')
job_stores = {'default': sqlalchemy_job_store}
executors = {'default': ThreadPoolExecutor(20)}
scheduler = BlockingScheduler(job_stores=job_stores, executors=executors)


def add(x, y):
    print("adding...")
    return x + y


logging.basicConfig(level=logging.DEBUG)
scheduler.add_job(add, 'interval', args=(6, 6), seconds=30)
scheduler.start()
```

**Comment by agronholm** [comment]
No response – closing for inactivity.
